### ISSUE TITLE
SecurityContextConstraints server could not find the requested resource

### ISSUE THREAD

**Issue by jamorales85** [kbst/terraform-provider-kustomization#108]
I'm trying to deploy a SecurityContextConstraints resource (in Openshift Cluster) with kustomize. When I make directly with kustomize it works properly, but with terraform I got this error:
```
Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceCreate: apiVersion: "security.openshift.io/v1", kind: "SecurityContextConstraints", namespace: "system-platform-devel" name: "my-cluster": create failed: the server could not find the requested resource

```

File is:
```
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: my-cluster
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
requiredDropCapabilities:
  - "ALL"
allowedCapabilities:
  - "FOWNER"
  - "CHOWN"
  - "DAC_OVERRIDE"
volumes:
  - "configMap"
  - "secret"
  - "persistentVolumeClaim"
  - "downwardAPI"
  - "emptyDir"
  - "projected"
```

And terraform code only fails in this point
