### ISSUE TITLE
Replica count gets ignored on apply when scaled manually

### ISSUE THREAD

**Issue by pietervisser** [kbst/terraform-provider-kustomization#118]
Hi,

When I have a my-deployment.yaml with 1 replica:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
```
And then run `terraform apply`, the deployment gets created with 1 pod as expected. When I then scale the deployment manually to 0 with `kubectl scale --replicas=0 deployment/my-deployment` the pod gets terminated. 

I would expect that running `terraform apply` again would result in changing the deployment, but terraform says everything is up to date. Is this expected behavior? This is different from using `kubectl apply -k ...` with kustomize, because this will result in changing the deployment and scaling it back to 1 pod again.
