### ISSUE TITLE
secrets_generator block not replacing base file sources 

### ISSUE THREAD

**Issue by tf-rob-w** [kbst/terraform-provider-kustomization#204]
I am trying to install Wazuh using [wazuh-kubernetes](https://github.com/wazuh/wazuh-kubernetes) which uses kustomize.

As part of this install, the base kustomiztion.yaml contains [two secretGenerator blocks](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/kustomization.yml#L14-L30), which each reference some local files.

In a manual install one would create these files and then `apply -k` the applicable overlay.

Using the `kustomization` provider, I'm attempting to create a new wrapper overlay that replaces these `secretGenerator` blocks:

```hcl
data "kustomization_overlay" "wazuh" {
  secret_generator {
    name     = "indexer-certs"
    behavior = "replace"
    files = [
      "${path.module}/certs/indexer_cluster/root-ca.pem",
      "${path.module}/certs/indexer_cluster/node.pem",
      "${path.module}/certs/indexer_cluster/node-key.pem",
      "${path.module}/certs/indexer_cluster/dashboard.pem",
      "${path.module}/certs/indexer_cluster/dashboard-key.pem",
      "${path.module}/certs/indexer_cluster/admin.pem",
      "${path.module}/certs/indexer_cluster/admin-key.pem",
      "${path.module}/certs/indexer_cluster/filebeat.pem",
      "${path.module}/certs/indexer_cluster/filebeat-key.pem",
    ]
  }

  secret_generator {
    name     = "dashboard-certs"
    behavior = "replace"
    files = [
      "${path.module}/certs/dashboard_http/cert.pem",
      "${path.module}/certs/dashboard_http/key.pem",
      "${path.module}/certs/indexer_cluster/root-ca.pem",
    ]
  }

  resources = [
    "https://github.com/wazuh/wazuh-kubernetes/wazuh?ref=v${local.wazuh_release}",
    "https://github.com/wazuh/wazuh-kubernetes/envs/eks?ref=v${local.wazuh_release}",
  ]

  kustomize_options {
    load_restrictor = "none"
  }
}
```

Using `behavior = replace`, I would expect the `secretGenerator` blocks to be overwritten, but running a `plan` produces an error as if the replacements do not happen:

```
╷
│ Error: buildKustomizeOverlay: Kustomizer Run for path '.' failed: accumulating resources: accumulation err='accumulating resources from 'https://github.com/wazuh/wazuh-kubernetes/wazuh?ref=v4.3.6': URL is a git repository': recursed accumulation of path '/private/var/folders/7k/ny4bb5qs2v57nn_fyd110hg00000gq/T/kustomize-835630976/wazuh': loading KV pairs: file sources: [certs/indexer_cluster/root-ca.pem certs/indexer_cluster/node.pem certs/indexer_cluster/node-key.pem certs/indexer_cluster/dashboard.pem certs/indexer_cluster/dashboard-key.pem certs/indexer_cluster/admin.pem certs/indexer_cluster/admin-key.pem certs/indexer_cluster/filebeat.pem certs/indexer_cluster/filebeat-key.pem]: evalsymlink failure on '/private/var/folders/7k/ny4bb5qs2v57nn_fyd110hg00000gq/T/kustomize-835630976/wazuh/certs/indexer_cluster/root-ca.pem' : lstat /private/var/folders/7k/ny4bb5qs2v57nn_fyd110hg00000gq/T/kustomize-835630976/wazuh/certs/indexer_cluster/root-ca.pem: no such file or directory
│
│   with data.kustomization_overlay.wazuh,
│   on wazuh.tf line 5, in data "kustomization_overlay" "wazuh":
│    5: data "kustomization_overlay" "wazuh" {
│
╵
```

Is this an issue, a known limitation, or am I just misinterpreting what is happening during the overlay creation?

**Edit:** Based on [this](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#overriding-base-configmap-values), I tried setting the `namespace` explicitly in my `secret_generator` blocks in the HCL above, but it did not change the behaviour.

**Comment by pst** [comment]
Try two things:
1. use resources on disk, not a remote URL, you reference resources under path.module but the path on disk is seems to be some temp checkout
1. try without the provider using `kustomize build` and a `kustomization.yaml`

**Comment by tf-rob-w** [comment]
Trying outside of the provider as you suggest results in the same. Here is my `kustomization.yaml`:

```yaml
bases:
  - ../eks

secretGenerator:
  - name: indexer-certs
    namespace: wazuh
    behavior: replace
    files:
      - certs/indexer_cluster/root-ca.pem
      - certs/indexer_cluster/node.pem
      - certs/indexer_cluster/node-key.pem
      - certs/indexer_cluster/dashboard.pem
      - certs/indexer_cluster/dashboard-key.pem
      - certs/indexer_cluster/admin.pem
      - certs/indexer_cluster/admin-key.pem
      - certs/indexer_cluster/filebeat.pem
      - certs/indexer_cluster/filebeat-key.pem
  - name: dashboard-certs
    namespace: wazuh
    behavior: replace
    files:
      - certs/dashboard_http/cert.pem
      - certs/dashboard_http/key.pem
      - certs/indexer_cluster/root-ca.pem
```

```
$ kustomize build --load-restrictor LoadRestrictionsNone
Error: accumulating resources: accumulation err='accumulating resources from '../eks': read /Users/rob.westbrook/src/testing/wazuh/wazuh-kubernetes/envs/eks: is a directory': recursed accumulation of path '/Users/rob.westbrook/src/testing/wazuh/wazuh-kubernetes/envs/eks': accumulating resources: accumulation err='accumulating resources from '../../wazuh': read /Users/rob.westbrook/src/testing/wazuh/wazuh-kubernetes/wazuh: is a directory': recursed accumulation of path '/Users/rob.westbrook/src/testing/wazuh/wazuh-kubernetes/wazuh': loading KV pairs: file sources: [certs/indexer_cluster/root-ca.pem certs/indexer_cluster/node.pem certs/indexer_cluster/node-key.pem certs/indexer_cluster/dashboard.pem certs/indexer_cluster/dashboard-key.pem certs/indexer_cluster/admin.pem certs/indexer_cluster/admin-key.pem certs/indexer_cluster/filebeat.pem certs/indexer_cluster/filebeat-key.pem]: open /Users/rob.westbrook/src/testing/wazuh/wazuh-kubernetes/wazuh/certs/indexer_cluster/root-ca.pem: no such file or directory
```

I'm not sure if this is just how kustomize works, or if it's a PEBKAC error, but regardless I think it proves that this is outside the remit of the provider to fix.
