### ISSUE TITLE
Replacements not working for TF provider, but work with kustomize build

### ISSUE THREAD

**Issue by sandangel** [kbst/terraform-provider-kustomization#228]
This terraform config does not replace NUMAFLOW_IMAGE env var value with the referenced image in `replacements`

```hcl
data "kustomization_overlay" "this" {
  images {
    name     = "quay.io/numaproj/numaflow"
    new_name = "quay.artifactory-ha.tri-ad.tech/numaproj/numaflow"
    new_tag  = "latest"
  }

  # Not working yet due to TF provider bug
  replacements {
    source {
      kind       = "Deployment"
      name       = "numaflow-controller"
      field_path = "spec.template.spec.containers.[name=controller-manager].image"
    }
    target {
      select {
        name      = "Deployment"
        kind      = "numaflow-controller"
      }
      field_paths = [
        "spec.template.spec.containers.[name=controller-manager].env.[name=NUMAFLOW_IMAGE].value"
      ]
    }
  }


  resources = concat([
    "https://github.com/numaproj/numaflow/config/cluster-install",
  ])
}
```

However, using kustomize works correctly:

```yaml
resources:
  - https://github.com/numaproj/numaflow/config/cluster-install

images:
  - name: quay.io/numaproj/numaflow
    newName: quay.artifactory-ha.tri-ad.tech/numaproj/numaflow

replacements:
  - source:
      name: numaflow-controller
      kind: Deployment
      fieldPath: spec.template.spec.containers.[name=controller-manager].image
    targets:
      - select:
          name: numaflow-controller
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=controller-manager].env.[name=NUMAFLOW_IMAGE].value

```
