### ISSUE TITLE
failed: json: unknown field "components"

### ISSUE THREAD

**Issue by minherz** [kbst/terraform-provider-kustomization#248]
### Description

When trying to use the component with the kustomization.yaml file that uses components I get the following error message:

```terminal
Error: kustomizationBuild: Kustomizer Run for path '/home/user/workdir/provisioning/kustomize/test' failed: json: unknown field "components"
│ 
│   with data.kustomization.test,
│   on test.tf line 58, in data "kustomization" "test":
│   58: data "kustomization" "test" {
```

The folder `/home/user/workdir/provisioning/kustomize` has only one file: `kustomization.yaml` that looks like the following:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/GoogleCloudPlatform/microservices-demo/kustomize/base?version=v0.8.1
components:
- github.com/GoogleCloudPlatform/microservices-demo/kustomize/components/google-cloud-operations?version=v0.8.1
```

The file `test.tf` looks like the following:

```yaml
data "kustomization" "test" {
  provider = kustomization

  path = var.filepath_manifest
}

resource "kustomization_resource" "test" {
  provider = kustomization

  for_each = data.kustomization.test.ids
  manifest = data.kustomization.test.manifests[each.value]
}
```

where the `filepath_manifst` input variable has the value `/home/user/workdir/provisioning/kustomize`.

### System Info
Terraform version: `Terraform v1.5.7 on linux_amd64`
Provider version: `0.2.0-beta.3`
