### ISSUE TITLE
Kustomize fails at showing expected plan for changes of ingress rule

### ISSUE THREAD

**Issue by xiaoxi-s** [kbst/terraform-provider-kustomization#254]
I am having the following ingress object. But it seems `terraform plan` fails at capturing the change of a new path added to the host. If I add a new service and a path to that service in this ingress object, the change isn't shown in terraform plan. For example, the new path below did not show in the plan output. 
```yaml
          - path: /(admin)(.*)
            pathType: Prefix
            backend:
              service:
                name: my-admin
                port:
                  number: 80
```

However, the plan does show the change if I switched the default backend. The workaround for now should be destroying and creating the ingress object. 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 15G
    kubernetes.io/ingress.class: 'nginx'

spec:
  tls:
    - hosts:
        - mydom.com
      secretName: tls-secret
  rules:
    - host: mydom.com
      http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: my-web
                port:
                  number: 80
  defaultBackend:
    service:
      name: my-web
      port:
        number: 80
```

### Additional Info

I have the patch for the hostname: 
```yaml
  - target:
      kind: Ingress
      name: my-ingress
    patch: |-
        - op: replace
           path: /spec/rules/0/host
           value: newdom.com
```
