### ISSUE TITLE
terraform crash while doing kustomization_build

### ISSUE THREAD

**Issue by marrau** [kbst/terraform-provider-kustomization#60]
While trying to do a kustomization_build with a remote kustomization-base with a few more resources, terraform keeps crashing. 

 From the crash.log it seems to me that the provider is crashing.
Calling `kustomize build` works fine and produces the expected resources.

# Expected behaviour
`terraform plan` finishes without a detected change

# Actual behaviour
`terraform plan` crashes

# Steps to reproduce

```
git clone https://gist.github.com/4b9e12a0944eb26cc9e7d19679a3ae2b.git
cd 4b9e12a0944eb26cc9e7d19679a3ae2b
terraform init
terraform plan
```
# Additional Info
Gist: https://gist.github.com/marrau/4b9e12a0944eb26cc9e7d19679a3ae2b

Terraform: v0.13.4
Kustomize: {Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}

**Comment by pst** [comment]
Thanks for reporting. Can you try without setting [`kubeconfig_path`](https://gist.github.com/marrau/4b9e12a0944eb26cc9e7d19679a3ae2b#file-main-tf-L11). I want to make sure that `kubeconfig_path = "notexists"` isn't the reason for the crash.

If this isn't it, I will have to debug myself to see what causes this.

**Comment by marrau** [comment]
I checked it and it seems not to be related to the kubeconfig_path. Terraform keeps crashing with or without that property set.
I have another kustomization call (just adding a namespace to the k8s-cluster) that actually works. 

The error also appears, when i leave the provider completely empty:

```
provider "kustomization" {}
```
Note: i have working kubeconfig.

**Comment by pst** [comment]
My initial impression from the stack trace is, that this originates in the kustomize code, not the provider code. May be related to the remote base, I don't actively support or test those. I will debug as soon as I have more time.

As a potential workaround, you can try to checkout that Git repository and change the `kustomization.yaml` to point to the local checkout instead of the remote resource.

**Comment by marrau** [comment]
Didn´t thought about this. I gave it a try, but with no luck.

```
git clone https://github.com/fluxcd/toolkit
```
```
# file: kustomization.yaml
bases:
  - ./toolkit/manifests/install
```

I added the crashlog for this to the gist https://gist.github.com/marrau/4b9e12a0944eb26cc9e7d19679a3ae2b#file-crashlog_with_local_base-log

**Comment by marrau** [comment]
Maybe the transformer is a problem. With the downloaded Kustomization i tried to narrow the problem down, because you said it looks more like "inside" the kustomize-api and the crash-log tells something about "loadAndConfigurePlugin".

And i actually happen to find something that does make a difference.

Inside the root-kustomization of the manifest i want to install is a "transformer" setup.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotk-system
resources:
  - namespace.yaml
  - ../bases/source-controller
  - ../bases/kustomize-controller
  - ../bases/notification-controller
  - ../bases/helm-controller
  - ../rbac
  - ../policies
transformers:
  - labels.yaml
```

If i remove/comment the transformer the terraform-provider does not crash and shows "No changes" as expected (because i have not setup a resource).
Also after i have setup a resource to apply the manifest, the plan is working as expected.

So i guess we can narrow this particular problem down to not being able to properly handle the transformer.

**Comment by pst** [comment]
Maybe try using `commonLabels` in the `kustomization.yaml` directly and remove the `transformers`. Just to verify: https://kubernetes-sigs.github.io/kustomize/guides/plugins/builtins/#_labeltransformer_

**Comment by marrau** [comment]
That works:
```
commonLabels:
  app.kubernetes.io/instance: gotk-system
```
So it is not the builtin-transformer itself, but handling it as a transformer-call.

Their transformer looks like this:
```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/instance: gotk-system
fieldSpecs:
  - path: metadata/labels
    create: true
```
I don´t see any difference to the example.
